# Generated by Django 3.0.6 on 2020-06-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200618_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='tipe',
            new_name='size',
        ),
    ]
