# Generated by Django 3.0.6 on 2020-06-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200618_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='size',
            new_name='tipe',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='tipe',
            new_name='size',
        ),
    ]
