# Generated by Django 3.0.6 on 2020-06-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200618_1355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together={('item', 'size')},
        ),
    ]
