# Generated by Django 3.0.6 on 2020-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200618_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topings',
            new_name='Toppings',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='tipe',
            new_name='category',
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='price_l',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
