# Generated by Django 3.0.6 on 2020-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200619_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toppings',
            name='include_in',
            field=models.ManyToManyField(to='orders.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('name', 'category')},
        ),
    ]
