# Generated by Django 3.0.6 on 2020-06-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200623_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='toppings',
            field=models.ManyToManyField(related_name='item', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
